replicaCount: 1

image:
  repository: minterteam/console-web
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  port: 80

ingress:
  domain: ""
  tlsname: ""
  #issuer: letsencrypt-http
  clusterissuer: letsencrypt-prod

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
